### ISSUE TITLE
can't get token

### ISSUE THREAD

**Issue by HassanMortazavi** [James1345/django-rest-knox#17]
hi
i have a error when i wanna get token with send post request to /api/auth/login  with basic Authorization header.

python 3.4    django 1.9.4

settings.py:

INSTALLED_APPS = [
    ....
    'rest_framework',
    'knox',
     ....
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',)
}

REST_KNOX = {
  'SECURE_HASH_ALGORITHM': 'cryptography.hazmat.primitives.hashes.SHA512',
  'AUTH_TOKEN_CHARACTER_LENGTH': 64,
  'TOKEN_TTL': 10,
  'USER_SERIALIZER': 'knox.serializers.UserSerializer',
}

urls.py:
from django.conf.urls import url, include
urlpatterns = [
  url(r'api/auth/', include('knox.urls'))
]

Internal Server Error: /api/auth/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.4/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/knox/views.py", line 19, in post
    token = AuthToken.objects.create(request.user)
  File "/usr/local/lib/python3.4/dist-packages/knox/models.py", line 14, in create
    digest = crypto.hash_token(token, salt)
  File "/usr/local/lib/python3.4/dist-packages/knox/crypto.py", line 32, in hash_token
    digest = hashes.Hash(sha(), backend=default_backend())
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/backends/__init__.py", line 21, in <listcomp>
    for ep in pkg_resources.iter_entry_points(
AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by James1345** [comment]
If you can still replicate this, what versions of pip, setuptools and cryptography are installed? Cryptography can be picky about its versions

**Comment by James1345** [comment]
Over a year with no activity. Closing
